"""Build core/stroke_font_data.py from the Hershey single-stroke fonts.

Usage (one-off, the generated file is committed):
    pip download Hershey-Fonts --no-deps -d hf && unzip hf/*.whl -d hf/x
    python -I tools/build_stroke_fonts.py hf/x

Only real single-line fonts are used; the duplex/triplex/bold/gothic cuts fake weight with
several parallel lines and would turn into filled areas with a pen.
Units match the built-in font: baseline y = 0, capital height = 2.0, y points up.
The Hershey data has no umlauts, so they are composed from the base letter plus two dots.
"""
import sys
from pathlib import Path

sys.path.insert(0, sys.argv[1])
from HersheyFonts import HersheyFonts  # noqa: E402

FONTS = [  # key, Hershey name, label
    ('sans', 'futural', 'Futura · Serifenlos'),
    ('roman', 'rowmans', 'Roman · Antiqua'),
    ('times', 'timesr', 'Times · Serifen'),
    ('times-italic', 'timesi', 'Times · Kursiv'),
    ('script', 'scripts', 'Schreibschrift · Script'),
    ('cursive', 'cursive', 'Kursive Handschrift'),
]
CAP = 2.0
DOT_LEN = .06
DOT_DX = .17
DOT_GAP = .22
CHARS = [chr(c) for c in range(32, 127)]
UMLAUTS = {'ä': 'a', 'ö': 'o', 'ü': 'u', 'Ä': 'A', 'Ö': 'O', 'Ü': 'U'}


def r(v):
    return round(v + 0.0, 3)


def build(hershey_name):
    font = HersheyFonts()
    font.load_default_font(hershey_name)
    glyphs = font.all_glyphs
    h = glyphs['H']
    ys = [y for s in h.strokes for _, y in s]
    baseline, cap_h = max(ys), max(ys) - min(ys)
    k = CAP / cap_h
    out = {}
    for ch in CHARS:
        g = glyphs.get(ch)
        if g is None:
            raise SystemExit(f'{hershey_name}: missing {ch!r}')
        strokes = [[(r((x - g.left_offset) * k), r((baseline - y) * k)) for x, y in s] for s in g.strokes]
        out[ch] = (r(g.char_width * k), strokes)
    for ch, base in UMLAUTS.items():
        adv, strokes = out[base]
        pts = [p for s in strokes for p in s]
        cx = (min(x for x, _ in pts) + max(x for x, _ in pts)) / 2
        y = max(y for _, y in pts) + DOT_GAP
        dots = [[(r(cx + d - DOT_LEN / 2), r(y)), (r(cx + d + DOT_LEN / 2), r(y))] for d in (-DOT_DX, DOT_DX)]
        out[ch] = (adv, strokes + dots)
    return out


def main():
    lines = ['"""Generated by tools/build_stroke_fonts.py - do not edit.',
             '',
             'Hershey Fonts (A. V. Hershey, U.S. National Bureau of Standards). Use is permitted for any',
             'purpose as long as this credit line is kept (see README, "Schriften").',
             '',
             'FONT_DATA[key] = (label, {char: (advance, [[(x, y), ...], ...])})',
             '"""',
             'FONT_DATA = {']
    for key, name, label in FONTS:
        lines.append(f'    {key!r}: ({label!r}, {{')
        for ch, (adv, strokes) in build(name).items():
            lines.append(f'        {ch!r}: ({adv}, {strokes!r}),')
        lines.append('    }),')
    lines.append('}')
    dest = Path(__file__).resolve().parent.parent / 'core' / 'stroke_font_data.py'
    dest.write_text('\n'.join(lines) + '\n', encoding='utf8')
    print('wrote', dest, dest.stat().st_size, 'bytes')


main()
